name: Print Name Workflow

on:
  workflow_dispatch:
    inputs:
      name:
        description: "Enter your name"
        required: true
        default: "Your Name"
    branches:
      - madhu_branch

jobs:
  print_name:
    runs-on: ubuntu-latest

    steps:
      - name: Print the name input
        run: echo "Hello, ${{ github.event.inputs.name }}!"
